import assert from "node:assert/strict";
import fs from "node:fs";
import { crearCodigoFamilia } from "../utils/familia";

const rules = fs.readFileSync("firestore.rules", "utf8");
const cloud = fs.readFileSync("utils/cloudFamilia.ts", "utf8");
const screen = fs.readFileSync("screens/Family.tsx", "utf8");
const movementSheet = fs.readFileSync("components/SpaceMovementSheet.tsx", "utf8");
const movementFields = fs.readFileSync("components/SpaceMovementFields.tsx", "utf8");
const categorySheet = fs.readFileSync("components/TransactionCategorySheet.tsx", "utf8");
const invitationSheet = fs.readFileSync("components/SpaceInvitationSheet.tsx", "utf8");
const membersSheet = fs.readFileSync("components/SpaceMembersSheet.tsx", "utf8");
const movementFilter = fs.readFileSync("components/MovementAllButton.tsx", "utf8");
const deletion = fs.readFileSync("utils/cloudSync.ts", "utf8");
const server = fs.readFileSync("functions/index.js", "utf8");

const codes = new Set(Array.from({ length: 200 }, crearCodigoFamilia));
assert.equal(codes.size, 200, "los códigos de prueba no se repiten");
for (const code of codes) assert.match(code, /^[A-HJ-NP-Z2-9]{8}$/, "el código evita caracteres confusos");

assert.match(rules, /function familyMember\(familyId\)/, "cada lectura comprueba la membresía");
assert.match(rules, /allow list: if verified\(\) && resource\.data\.createdBy == request\.auth\.uid;/, "solo el creador puede buscar sus propios códigos para eliminarlos");
assert.match(rules, /expiresAt > request\.time\.toMillis\(\)/, "un código vencido no permite entrar");
assert.match(rules, /request\.resource\.data\.inviteCode/, "la membresía exige la invitación usada");
assert.match(rules, /function premiumUser\(userId\)/, "crear e invitar está protegido por Premium en Firebase");
assert.match(rules, /resource\.data\.personalOwnerUid == request\.auth\.uid/, "otro miembro no puede devolver a su favor un aporte de Personal");
assert.match(cloud, /familyUsers/, "el espacio se recupera al cambiar de celular");
assert.match(cloud, /export async function renombrarFamilia/, "el propietario puede guardar el nuevo nombre en la nube");
assert.match(cloud, /serverTimestamp\(\)/, "los movimientos usan la hora confiable de Firebase");
assert.match(screen, /sanitizeSafeAmountInput/, "Familia conserva el límite seguro para montos");
assert.doesNotMatch(screen, /MoreVertical|family\.options/, "la tarjeta de Familia ya no muestra el menú de tres puntos");
assert.match(screen, /t\("family\.members"\)[\s\S]*?\{miembros\.length\}/, "el botón de miembros muestra su texto y la cantidad actual");
assert.match(screen, /<SpaceMembersSheet familyName=\{familia\.nombre\} members=\{miembros\}/, "el botón de miembros abre una hoja con la lista de Familia");
assert.match(membersSheet, /canManage && member\.rol !== "owner"[\s\S]*?onRemove\(member\)/, "el propietario puede retirar miembros desde la hoja compacta");
assert.match(screen, /onOrigin=\{owner \? setOrigenDinero : undefined\}/, "solo el dueño controla el origen del dinero en ingresos familiares");
assert.match(movementFilter, /text-\[14px\] font-extrabold/, "el filtro de movimientos baja solo un poco el tamaño del texto en los tres espacios");
assert.match(movementSheet, /\[\"externo\", \"personal\"\] as const/, "el formulario permite distinguir dinero externo de Personal");
assert.match(movementSheet, /onOrigin\(value\)/, "el formulario aplica el origen seleccionado");
assert.match(movementSheet, /TransactionCategorySheet/, "Familia usa el selector actual de categorías");
assert.match(movementSheet, /gastosDisponibles, ingresosDisponibles/, "Familia ofrece categorías filtradas por ingreso o gasto");
assert.match(movementFields, /onOpenCategory/, "el campo familiar abre el selector reutilizable");
assert.doesNotMatch(movementFields, /<Modal|EXPENSE_CATS|INCOME_CATS/, "Familia ya no conserva el selector antiguo de categorías");
assert.match(categorySheet, /chooseImage\("camera"\)/, "la categoría familiar acepta foto de cámara");
assert.match(categorySheet, /chooseImage\("library"\)/, "la categoría familiar acepta foto de galería");
assert.match(categorySheet, /onPress=\{saveCategory\}/, "la categoría familiar se guarda desde la misma hoja");
assert.match(screen, /width: owner \? "48%" : "100%", height: 40/, "Agregar dinero ocupa el mismo ancho que Cerrar familia y se expande si no hay botón de cierre");
assert.doesNotMatch(screen, /SpaceActionBar/, "Familia no conserva el botón + flotante redundante");
assert.match(screen, /style=\{\{ width: "48%", height: 40 \}\} accessibilityRole="button" accessibilityLabel=\{t\("family\.close"\)\} disabled=\{ocupado\} onPress=\{cerrarFamiliaActiva\}/, "Cerrar familia conserva el mismo ancho y su acción accesible");
assert.ok(screen.indexOf("family.returnAmount") < screen.indexOf("width: owner ? \"48%\" : \"100%\", height: 40"), "Devolver dinero aparece encima de Agregar dinero y Cerrar familia");
assert.match(screen, /personalOwnerUid: uid/, "el aporte familiar recuerda a qué propietario pertenece");
assert.match(invitationSheet, /import\("expo-clipboard"\)[\s\S]*?clipboard\.setStringAsync\(code\)/, "la hoja carga el portapapeles al copiar, para que no tumbe la pantalla Familia");
assert.match(invitationSheet, /family\.copyCode/, "el botón de copiar tiene etiqueta accesible");
assert.match(screen, /SpaceInvitationSheet code=\{invitacion\}/, "el código aparece en una hoja y no debajo del historial");
assert.match(screen, /<View className="mt-2 flex-row items-center justify-between">[\s\S]*?t\("family\.all"\)[\s\S]*?family\.inviteAccessibility[\s\S]*?<\/View>\s*<View className="mt-2 rounded-3xl bg-emerald-600/, "la invitación de Familia comparte la fila de Ver todas y queda fuera de la tarjeta de saldo");
assert.match(screen, /MovementAllButton label=\{t\("family\.history"\)\}[\s\S]*?filterIncome[\s\S]*?filterExpense[\s\S]*?family\.selectMovements[\s\S]*?<\/>}/, "el filtro familiar usa una sola fila, igual que Personal");
assert.doesNotMatch(screen, /t\("family\.holdToCopy"\)/, "la tarjeta de código ya no ocupa espacio con una instrucción debajo");
assert.match(screen, /deleteLinkedTransferTransaction\(item\.personalTransactionId\)/, "el dueño recupera en Personal un aporte familiar que elimina desde Familia");
assert.match(screen, /planSpaceMovementDeletion\(movimientos, ids\)/, "Familia usa el mismo plan seguro de borrado que Caja");
assert.match(screen, /movementIdsForCompactRow\(\{ key, item, transferGroup \}, visibles\)/, "la tarjeta familiar agrupada selecciona ambas mitades enlazadas");
assert.match(screen, /countSelectedCompactRows\(filasVisibles, visibles, seleccionados\)/, "el contador familiar cuenta las tarjetas visibles, no los registros internos");
assert.match(screen, /spaces\.deleteLinkedMovementsMessage/, "la confirmación explica por qué la transferencia agrupada cuenta dos registros");
assert.match(cloud, /export async function quitarMiembroFamilia/, "el propietario puede retirar miembros de Familia");
assert.match(screen, /returnableToPersonal\(movimientos, auth\.currentUser\?\.uid\)/, "Familia solo devuelve a Personal el aporte que todavía queda");
assert.match(screen, /canSpendFromSpace\(movimientos, value\)/, "Familia impide gastar más que su saldo");
assert.match(screen, /minimumContributionAmount/, "editar un aporte familiar respeta lo ya utilizado");
assert.match(screen, /repairLinkedTransferTransactions/, "Familia repara transferencias huérfanas");
assert.match(cloud, /cerrarEspacioCompartido\("family", familiaId\)/, "Familia delega el cierre al servidor");
assert.match(server, /exports\.manageLinkedSpace[\s\S]*canCloseLinkedSpace\(movements\)/, "el servidor impide cerrar con saldo o aportes Personal pendientes");
assert.match(deletion, /borrarVinculoFamiliaDeCuenta/, "eliminar la cuenta también retira su membresía familiar");

console.log("Familia: invitaciones, membresía, vencimiento y privacidad verificados.");
