import { useRouter } from "expo-router";
import { ArrowLeft, CheckCircle2, Clock3 } from "lucide-react-native";
import { ScrollView, Text, TouchableOpacity, View } from "react-native";

export default function CreditCalendar() {
  const router = useRouter();
  const rows = [["1 de 6", "05 sep 2026", "S/ 125", "Próxima", "2 días"],["2 de 6", "05 oct 2026", "S/ 125", "Pendiente", "32 días"],["3 de 6", "05 nov 2026", "S/ 125", "Pendiente", "63 días"],["4 de 6", "05 dic 2026", "S/ 125", "Pendiente", "93 días"],["5 de 6", "05 ene 2027", "S/ 125", "Pendiente", "124 días"],["6 de 6", "05 feb 2027", "S/ 125", "Pagada", "—"]];
  return <ScrollView className="flex-1 bg-white px-4 pt-14"><TouchableOpacity onPress={() => useRouter().back()}><ArrowLeft color="#0f766e"/></TouchableOpacity><Text className="mt-4 text-2xl font-extrabold text-slate-900">Calendario de pagos</Text><View className="mt-4 rounded-2xl bg-emerald-700 p-4"><Text className="text-xl font-bold text-white">Scotiabank</Text><View className="mt-4 flex-row justify-between"><View><Text className="text-emerald-100">Vencimiento</Text><Text className="font-bold text-white">05 sep 2026</Text></View><View><Text className="text-emerald-100">Último día de pago</Text><Text className="font-bold text-white">15 sep 2026</Text></View></View></View><View className="mt-4 rounded-2xl border border-slate-200"><View className="flex-row justify-between bg-slate-100 p-3"><Text className="font-bold">Cuota</Text><Text className="font-bold">Fecha</Text><Text className="font-bold">Estado</Text></View>{rows.map((r,i)=><View key={i} className="flex-row items-center justify-between border-t border-slate-100 p-3"><Text>{r[0]}</Text><Text>{r[1]}</Text><View className={`rounded-full px-2 py-1 ${r[3]==="Pagada"?"bg-emerald-100":"bg-amber-100"}`}><Text className="text-xs font-bold">{r[3]}</Text></View></View>)}</View><View className="mt-5 flex-row items-center rounded-2xl bg-amber-50 p-4"><Clock3 color="#b45309" size={22}/><Text className="ml-3 flex-1 text-amber-900">Próximo pago en 2 días</Text></View><TouchableOpacity className="mt-5 mb-10 rounded-2xl bg-emerald-600 p-4"><View className="flex-row items-center justify-center"><CheckCircle2 color="white"/><Text className="ml-2 font-bold text-white">Marcar como pagada</Text></View></TouchableOpacity></ScrollView>;
}
