import type { LanguageId } from "@/constants/i18n";
import { esFoto } from "@/utils/iconosFavoritos";

// Rótulos del dibujo REAL, no de la categoría contable. Sin cargar tipografías,
// red ni contexto por casilla. No se anuncia un URI o base64 de fotos propias.
export const ICON_ACCESSIBILITY_NAMES: Readonly<Record<string, readonly [string, string, string]>> = {
  "Utensils": ["Tenedor y cuchillo","Fork and knife","Garfo e faca"],
  "UtensilsCrossed": ["Cubiertos","Cutlery","Talheres"],
  "Coffee": ["Café","Coffee","Café"],
  "Pizza": ["Pizza","Pizza","Pizza"],
  "Beef": ["Carne","Steak","Carne"],
  "Sandwich": ["Hamburguesa","Hamburger","Hambúrguer"],
  "IceCreamCone": ["Helado","Ice cream","Sorvete"],
  "CakeSlice": ["Pastel","Cake","Bolo"],
  "Apple": ["Manzana","Apple","Maçã"],
  "Carrot": ["Zanahoria","Carrot","Cenoura"],
  "Fish": ["Pescado","Fish","Peixe"],
  "EggFried": ["Huevo frito","Fried egg","Ovo frito"],
  "Beer": ["Cerveza","Beer","Cerveja"],
  "Wine": ["Vino","Wine","Vinho"],
  "CupSoda": ["Vaso","Cup","Copo"],
  "Milk": ["Botella","Bottle","Garrafa"],
  "Croissant": ["Croissant","Croissant","Croissant"],
  "Soup": ["Tazón","Bowl","Tigela"],
  "Salad": ["Hoja","Leaf","Folha"],
  "Cookie": ["Galleta","Cookie","Biscoito"],
  "Popcorn": ["Palomitas","Popcorn","Pipoca"],
  "Candy": ["Caramelo","Candy","Bala"],
  "Ham": ["Cerdo","Pig","Porco"],
  "Drumstick": ["Muslo de pollo","Chicken drumstick","Coxa de frango"],
  "Car": ["Auto","Car","Carro"],
  "Bus": ["Autobús","Bus","Ônibus"],
  "TrainFront": ["Tren","Train","Trem"],
  "Plane": ["Avión","Airplane","Avião"],
  "Bike": ["Bicicleta","Bicycle","Bicicleta"],
  "Fuel": ["Combustible","Fuel","Combustível"],
  "CircleParking": ["Estacionamiento","Parking","Estacionamento"],
  "TramFront": ["Tranvía","Tram","Bonde"],
  "Ship": ["Barco","Ship","Navio"],
  "Truck": ["Camión","Truck","Caminhão"],
  "CarTaxiFront": ["Taxi","Taxi","Táxi"],
  "Footprints": ["Huellas","Footprints","Pegadas"],
  "Sailboat": ["Velero","Sailboat","Veleiro"],
  "Caravan": ["Casa rodante","Camper van","Motorhome"],
  "Ambulance": ["Ambulancia","Ambulance","Ambulância"],
  "ShoppingBag": ["Bolsa de compras","Shopping bag","Sacola de compras"],
  "ShoppingCart": ["Carrito de compras","Shopping cart","Carrinho de compras"],
  "ShoppingBasket": ["Canasta","Basket","Cesta"],
  "Store": ["Tienda","Store","Loja"],
  "Tag": ["Etiqueta","Tag","Etiqueta"],
  "Tags": ["Etiquetas","Tags","Etiquetas"],
  "Gift": ["Regalo","Gift","Presente"],
  "Package": ["Paquete","Package","Pacote"],
  "Shirt": ["Camiseta","Shirt","Camiseta"],
  "Watch": ["Reloj de pulsera","Watch","Relógio de pulso"],
  "Glasses": ["Lentes","Glasses","Óculos"],
  "Gem": ["Diamante","Diamond","Diamante"],
  "Backpack": ["Mochila","Backpack","Mochila"],
  "Baby": ["Coche de bebé","Baby carriage","Carrinho de bebê"],
  "Film": ["Película","Movie","Filme"],
  "Gamepad2": ["Control de videojuegos","Game controller","Controle de jogos"],
  "Music": ["Música","Music","Música"],
  "Tv": ["Televisión","Television","Televisão"],
  "Ticket": ["Entrada","Ticket","Ingresso"],
  "Drama": ["Teatro","Theater","Teatro"],
  "Guitar": ["Guitarra","Guitar","Violão"],
  "Headphones": ["Audífonos","Headphones","Fones de ouvido"],
  "PartyPopper": ["Fiesta","Party","Festa"],
  "Dices": ["Dados","Dice","Dados"],
  "Puzzle": ["Rompecabezas","Puzzle","Quebra-cabeça"],
  "Clapperboard": ["Claqueta","Clapperboard","Claquete"],
  "Radio": ["Radio","Radio","Rádio"],
  "Mic": ["Micrófono","Microphone","Microfone"],
  "Camera": ["Cámara","Camera","Câmera"],
  "BookOpen": ["Libro abierto","Open book","Livro aberto"],
  "Palette": ["Paleta de pintura","Paint palette","Paleta de pintura"],
  "House": ["Casa","House","Casa"],
  "Sofa": ["Sofá","Sofa","Sofá"],
  "Bed": ["Cama","Bed","Cama"],
  "Lamp": ["Lámpara","Lamp","Lâmpada"],
  "Refrigerator": ["Refrigerador","Refrigerator","Geladeira"],
  "WashingMachine": ["Lavadora","Washing machine","Máquina de lavar"],
  "ShowerHead": ["Ducha","Shower","Chuveiro"],
  "Toilet": ["Inodoro","Toilet","Vaso sanitário"],
  "Armchair": ["Sillón","Armchair","Poltrona"],
  "DoorOpen": ["Puerta abierta","Open door","Porta aberta"],
  "Wrench": ["Llave de herramientas","Wrench","Chave de ferramentas"],
  "Hammer": ["Martillo","Hammer","Martelo"],
  "PaintRoller": ["Rodillo de pintura","Paint roller","Rolo de pintura"],
  "Plug": ["Enchufe","Plug","Tomada"],
  "Trash2": ["Papelera","Trash can","Lixeira"],
  "Flower2": ["Flor","Flower","Flor"],
  "TreePine": ["Pino","Pine tree","Pinheiro"],
  "Blinds": ["Persianas","Blinds","Persianas"],
  "HeartPulse": ["Corazón y pulso","Heart and pulse","Coração e pulso"],
  "Pill": ["Pastilla","Pill","Comprimido"],
  "Stethoscope": ["Estetoscopio","Stethoscope","Estetoscópio"],
  "Syringe": ["Jeringa","Syringe","Seringa"],
  "Cross": ["Botiquín","First aid kit","Kit de primeiros socorros"],
  "Activity": ["Pulso","Pulse","Pulso"],
  "Brain": ["Cerebro","Brain","Cérebro"],
  "Eye": ["Ojo","Eye","Olho"],
  "Bandage": ["Vendaje","Bandage","Curativo"],
  "Thermometer": ["Termómetro","Thermometer","Termômetro"],
  "Hospital": ["Hospital","Hospital","Hospital"],
  "GraduationCap": ["Gorro de graduación","Graduation cap","Chapéu de formatura"],
  "Book": ["Libro","Book","Livro"],
  "Library": ["Estantería de libros","Bookshelf","Estante de livros"],
  "Pencil": ["Lápiz","Pencil","Lápis"],
  "NotebookPen": ["Cuaderno y lápiz","Notebook and pencil","Caderno e lápis"],
  "School": ["Escuela","School","Escola"],
  "Calculator": ["Calculadora","Calculator","Calculadora"],
  "Microscope": ["Microscopio","Microscope","Microscópio"],
  "Ruler": ["Regla","Ruler","Régua"],
  "Briefcase": ["Maletín","Briefcase","Maleta"],
  "Laptop": ["Computadora portátil","Laptop","Notebook"],
  "TrendingUp": ["Tendencia creciente","Upward trend","Tendência crescente"],
  "Crown": ["Corona","Crown","Coroa"],
  "HandCoins": ["Mano con moneda","Hand with coin","Mão com moeda"],
  "Key": ["Llave","Key","Chave"],
  "Coins": ["Dinero","Money","Dinheiro"],
  "Wallet": ["Billetera","Wallet","Carteira"],
  "CreditCard": ["Tarjeta","Card","Cartão"],
  "Banknote": ["Billete","Banknote","Nota"],
  "PiggyBank": ["Alcancía","Piggy bank","Cofrinho"],
  "Receipt": ["Recibo","Receipt","Recibo"],
  "Landmark": ["Banco","Bank","Banco"],
  "ChartColumn": ["Gráfico de barras","Bar chart","Gráfico de barras"],
  "ChartPie": ["Gráfico circular","Pie chart","Gráfico circular"],
  "Handshake": ["Apretón de manos","Handshake","Aperto de mãos"],
  "Percent": ["Porcentaje","Percentage","Porcentagem"],
  "Trophy": ["Trofeo","Trophy","Troféu"],
  "Medal": ["Medalla","Medal","Medalha"],
  "BadgeDollarSign": ["Pago confirmado","Confirmed payment","Pagamento confirmado"],
  "Zap": ["Rayo","Lightning","Raio"],
  "Droplet": ["Gota de agua","Water drop","Gota de água"],
  "Flame": ["Fuego","Fire","Fogo"],
  "Wifi": ["Wifi","Wi-Fi","Wi-Fi"],
  "Phone": ["Teléfono","Telephone","Telefone"],
  "Smartphone": ["Celular","Mobile phone","Celular"],
  "Signal": ["Señal","Signal","Sinal"],
  "Cloud": ["Nube","Cloud","Nuvem"],
  "Repeat": ["Repetir","Repeat","Repetir"],
  "CalendarClock": ["Calendario con reloj","Calendar with clock","Calendário com relógio"],
  "Router": ["Router","Router","Roteador"],
  "MonitorSmartphone": ["Computadora y celular","Computer and phone","Computador e celular"],
  "PawPrint": ["Huella de mascota","Paw print","Pegada de animal"],
  "Dog": ["Perro","Dog","Cachorro"],
  "Cat": ["Gato","Cat","Gato"],
  "Bird": ["Pájaro","Bird","Pássaro"],
  "Bone": ["Hueso","Bone","Osso"],
  "Rabbit": ["Conejo","Rabbit","Coelho"],
  "Turtle": ["Tortuga","Turtle","Tartaruga"],
  "Dumbbell": ["Pesas","Dumbbell","Pesos"],
  "Volleyball": ["Pelota de vóley","Volleyball","Bola de vôlei"],
  "WavesHorizontal": ["Olas","Waves","Ondas"],
  "Mountain": ["Montaña","Mountain","Montanha"],
  "Tent": ["Carpa","Tent","Barraca"],
  "Target": ["Objetivo","Target","Alvo"],
  "Timer": ["Cronómetro","Stopwatch","Cronômetro"],
  "Ellipsis": ["Puntos suspensivos","Ellipsis","Reticências"],
  "Star": ["Estrella","Star","Estrela"],
  "Heart": ["Corazón","Heart","Coração"],
  "Bookmark": ["Marcador","Bookmark","Marcador"],
  "Flag": ["Bandera","Flag","Bandeira"],
  "MapPin": ["Ubicación","Location pin","Localização"],
  "Calendar": ["Calendario","Calendar","Calendário"],
  "Clock": ["Reloj","Clock","Relógio"],
  "Users": ["Grupo de personas","Group of people","Grupo de pessoas"],
  "User": ["Persona","Person","Pessoa"],
  "Shield": ["Escudo","Shield","Escudo"],
  "Sparkles": ["Destellos","Sparkles","Brilhos"],
  "Lightbulb": ["Bombilla","Light bulb","Lâmpada"],
  "Rocket": ["Cohete","Rocket","Foguete"],
  "Anchor": ["Ancla","Anchor","Âncora"],
  "Umbrella": ["Paraguas","Umbrella","Guarda-chuva"],
  "Snowflake": ["Copo de nieve","Snowflake","Floco de neve"],
  "Sun": ["Sol","Sun","Sol"],
  "PlusCircle": ["Más en círculo","Plus in circle","Mais em círculo"],
};
const BRANDS: Readonly<Record<string, string>> = {
  "marca:youtube": "YouTube",
  "marca:spotify": "Spotify",
  "marca:soundcloud": "SoundCloud",
  "marca:deezer": "Deezer",
  "marca:itunes": "iTunes",
  "marca:napster": "Napster",
  "marca:audible": "Audible",
  "marca:vimeo": "Vimeo",
  "marca:dailymotion": "Dailymotion",
  "marca:imdb": "IMDb",
  "marca:steam": "Steam",
  "marca:playstation": "PlayStation",
  "marca:xbox": "Xbox",
  "marca:twitch": "Twitch",
  "marca:itch-io": "Itch.io",
  "marca:battle-net": "Battle.net",
  "marca:unity": "Unity",
  "marca:discord": "Discord",
  "marca:instagram": "Instagram",
  "marca:facebook": "Facebook",
  "marca:whatsapp": "WhatsApp",
  "marca:telegram": "Telegram",
  "marca:tiktok": "TikTok",
  "marca:twitter": "Twitter",
  "marca:snapchat": "Snapchat",
  "marca:reddit": "Reddit",
  "marca:pinterest": "Pinterest",
  "marca:linkedin": "LinkedIn",
  "marca:amazon": "Amazon",
  "marca:ebay": "eBay",
  "marca:shopify": "Shopify",
  "marca:etsy": "Etsy",
  "marca:google-play": "Google Play",
  "marca:app-store": "App Store",
  "marca:uber": "Uber",
  "marca:airbnb": "Airbnb",
  "marca:dropbox": "Dropbox",
  "marca:patreon": "Patreon",
  "marca:kickstarter": "Kickstarter",
  "marca:goodreads": "Goodreads",
  "marca:wordpress": "WordPress",
  "marca:apple": "Apple",
  "marca:android": "Android",
  "marca:windows": "Windows",
  "marca:microsoft": "Microsoft",
  "marca:google": "Google",
  "marca:chrome": "Chrome",
  "marca:firefox": "Firefox",
  "marca:github": "GitHub",
  "marca:gitlab": "GitLab",
  "marca:figma": "Figma",
  "marca:slack": "Slack",
  "marca:trello": "Trello",
  "marca:ubuntu": "Ubuntu",
  "marca:docker": "Docker",
};
export function iconLabelFor(id: string, language: string): string {
  const index = ({ es: 0, en: 1, pt: 2 } as Record<LanguageId, number>)[language as LanguageId] ?? 0;
  if (esFoto(id)) return ["Foto propia", "Your photo", "Sua foto"][index];
  const name = ICON_ACCESSIBILITY_NAMES[id]?.[index] ?? BRANDS[id];
  return name ?? ["Dibujo no disponible", "Unavailable icon", "Ícone indisponível"][index];
}
